/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function asyncPinyin(input: string | Buffer, opt?: PinyinConvertOptions | undefined | null, signal?: AbortSignal | undefined | null): Promise<string[] | string[][]>

export declare function compare(inputA: string, inputB: string): number

export declare function pinyin(input: string | Uint8Array, opt?: PinyinConvertOptions | undefined | null): string[] | string[][]

/** 拼音风格 */
export declare const enum PINYIN_STYLE {
  /** 普通风格，不带声调 */
  Plain = 0,
  /** 带声调的风格 */
  WithTone = 1,
  /** 声调在各个拼音之后，使用数字1-4表示的风格 */
  WithToneNum = 2,
  /** 声调在拼音最后，使用数字1-4表示的风格 */
  WithToneNumEnd = 3,
  /** 首字母风格 */
  FirstLetter = 4
}

export interface PinyinConvertOptions {
  style?: PINYIN_STYLE
  heteronym?: boolean
  segment?: boolean
}
