/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 拼音风格 */
export const enum PINYIN_STYLE {
  /** 普通风格，不带声调 */
  Plain = 0,
  /** 带声调的风格 */
  WithTone = 1,
  /** 声调在各个拼音之后，使用数字1-4表示的风格 */
  WithToneNum = 2,
  /** 声调在拼音最后，使用数字1-4表示的风格 */
  WithToneNumEnd = 3,
  /** 首字母风格 */
  FirstLetter = 4,
}
export interface PinyinConvertOptions {
  style?: PINYIN_STYLE
  heteronym?: boolean
  segment?: boolean
}
interface HeteronymPinyinConvertOptions extends PinyinConvertOptions {
  heteronym: true
}
export function pinyin(inputStr: string, opt: HeteronymPinyinConvertOptions): string[][]
export function pinyin(inputStr: string, opt?: PinyinConvertOptions | undefined | null): string[]
export function asyncPinyin(
  input: string,
  opt: HeteronymPinyinConvertOptions,
  signal?: AbortSignal | undefined | null,
): Promise<string[][]>
export function asyncPinyin(
  input: string,
  opt?: PinyinConvertOptions | undefined | null,
  signal?: AbortSignal | undefined | null,
): Promise<string[]>
export function compare(inputA: string, inputB: string): number
