/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare function asyncPinyin(input: string | Buffer, opt?: PinyinConvertOptions | undefined | null, signal?: AbortSignal | undefined | null): Promise<string[] | string[][]>

export declare function compare(inputA: string, inputB: string): number

export declare function pinyin(input: string | Uint8Array, opt?: PinyinConvertOptions | undefined | null): string[] | string[][]

/** 拼音风格 */
export declare const enum PINYIN_STYLE {
  /** 普通风格，不带声调 */
  Plain = 0,
  /** 带声调的风格 */
  WithTone = 1,
  /** 声调在各个拼音之后，使用数字1-4表示的风格 */
  WithToneNum = 2,
  /** 声调在拼音最后，使用数字1-4表示的风格 */
  WithToneNumEnd = 3,
  /** 首字母风格 */
  FirstLetter = 4,
}

export interface PinyinConvertOptions {
  style?: PINYIN_STYLE
  heteronym?: boolean
  /** Resolve dictionary phrases. With heteronym, all character readings are returned. */
  segment?: boolean
  /** Resolver used when segment is true. Defaults to phrase. Jieba uses HMM=false. */
  segmenter?: 'phrase' | 'jieba'
}

/** Convert directly to one string, avoiding a JS allocation for each syllable. */
export declare function pinyinString(input: string | Uint8Array, opt?: PinyinStringOptions | undefined | null): string

export interface PinyinStringOptions {
  style?: PINYIN_STYLE
  segment?: boolean
  /** Resolver used when segment is true. Defaults to phrase. Jieba uses HMM=false. */
  segmenter?: 'phrase' | 'jieba'
  /** Separator between syllables and unchanged non-Han runs. Defaults to a space. */
  separator?: string
}
